default_language_version:
  python: python3

exclude: |
  (?x)^(
    .*thirdparty/.*
  )

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
        types_or: [text]
        args: [--dry-run, --Werror] # Only report issues, don't fix automatically

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
        args: [--quiet, --use-color]
        types_or: [text]
        additional_dependencies: [clang-tidy==19.1.0]
        require_serial: true
        stages: [manual] # Not automatically triggered, invoked via `pre-commit run --hook-stage manual clang-tidy`
